name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - add-ci-build
jobs:
  build: 
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres: 
        image: postgres:alpine
        port: 
          - 5432:5432
        env: 
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interva 10s
          --health-timeout 5s
          --health-retries 5

          run: docker run -d --name postgres -p 5432:5432 \
              -e POSTGRES_PASSWORD=pgs3cr3t \
              -v postgres:/var/lib/postgresql/data \
              postgres:alpine
      